Conhecendo o Python


Bem vindo(a) ao estudo da linguagem Python

In [4]:
x = 1
y = 2
print("X vale:", x)
print("Y vale:", y)

X vale: 1
Y vale: 2

In [5]:
x+y

3

In [7]:
x = "Data "
y = "Science "
print(x+y)

Data Science

In [9]:
True + True + False

2

In [8]:
None

Conhecendo os Tipos

In [10]:
teste = 1
type(teste)

int

In [11]:
int(3.15)

3

## Trabalhando com o Pandas

In [16]:
import pandas as pd

serie = pd.Series([3,7,5,6,8])
serie

0    3
1    7
2    5
3    6
4    8
dtype: int64

In [37]:
serie.head(3)

0    3
1    7
2    5
dtype: int64

In [21]:
serie.dtype

dtype('int64')

In [22]:
serie.isnull()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [23]:
serie.value_counts()

3    1
7    1
5    1
6    1
8    1
Name: count, dtype: int64

In [26]:
data_int = pd.date_range("20250101", periods=6, freq="ME")

In [29]:
data_br = data_int.strftime("%d/%m/$Y")
data_br

Index(['31/01/$Y', '28/02/$Y', '31/03/$Y', '30/04/$Y', '31/05/$Y', '30/06/$Y'], dtype='object')

In [36]:
import numpy as np

df = pd.DataFrame(
    np.random.randint(1,5,size=(6,4)),
    index=data_br,
    columns=["A", "B", "C", "D"]
    )

In [38]:
df.head(3)

          A  B  C  D
31/01/$Y  3  1  3  2
28/02/$Y  1  2  3  2
31/03/$Y  4  2  4  3

In [39]:
df.columns = ['a', 'b', 'c', 'd']

In [40]:
df.columns = ['coll', 'col2', 'col3', 'col4']

In [41]:
df

          coll  col2  col3  col4
31/01/$Y     3     1     3     2
28/02/$Y     1     2     3     2
31/03/$Y     4     2     4     3
30/04/$Y     4     1     3     4
31/05/$Y     1     2     2     1
30/06/$Y     4     4     4     4